policy:
  approval:
  - or:
    - Dependabot or renovate update
    - Code change

approval_rules:
- name: Dependabot or renovate update
  if:
    only_has_contributors_in:
      users:
      - dependabot[bot]
      - renovate-coop-norge[bot]
    only_changed_files:
      paths:
      - .*
    has_valid_signatures_by_keys:
      key_ids:
      - B5690EEEBB952194
  requires:
    count: 1
    teams:
    - coopnorge/github-review-bots
    - coopnorge/cloud-platform
  options:
    invalidate_on_push: true
    methods:
      github_review: true
      comments: []

- name: Code change
  if:
    changed_files:
      paths:
      - .*
  requires:
    count: 1
    teams:
    - coopnorge/cloud-platform
  options:
    invalidate_on_push: true
    methods:
      github_review: true
      comments: []
