// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/coopnorge/provider-upjet-spacelift/apis/stack/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this GcpServiceAccount.
func (mg *GcpServiceAccount) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.StackID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.StackIDRef,
		Selector:     mg.Spec.ForProvider.StackIDSelector,
		To: reference.To{
			List:    &v1alpha1.StackList{},
			Managed: &v1alpha1.Stack{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.StackID")
	}
	mg.Spec.ForProvider.StackID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.StackIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.StackID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.StackIDRef,
		Selector:     mg.Spec.InitProvider.StackIDSelector,
		To: reference.To{
			List:    &v1alpha1.StackList{},
			Managed: &v1alpha1.Stack{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.StackID")
	}
	mg.Spec.InitProvider.StackID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.StackIDRef = rsp.ResolvedReference

	return nil
}
