// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AttachmentInitParameters struct {

	// (String) ID of the context to attach
	// ID of the context to attach
	// +crossplane:generate:reference:type=github.com/aksel-allas-org/provider-spacelift/apis/context/v1alpha1.Context
	ContextID *string `json:"contextId,omitempty" tf:"context_id,omitempty"`

	// Reference to a Context in context to populate contextId.
	// +kubebuilder:validation:Optional
	ContextIDRef *v1.Reference `json:"contextIdRef,omitempty" tf:"-"`

	// Selector for a Context in context to populate contextId.
	// +kubebuilder:validation:Optional
	ContextIDSelector *v1.Selector `json:"contextIdSelector,omitempty" tf:"-"`

	// (String) ID of the module to attach the context to
	// ID of the module to attach the context to
	ModuleID *string `json:"moduleId,omitempty" tf:"module_id,omitempty"`

	// (Number) Priority of the context attachment. All the contexts attached to a stack are sorted by priority (lowest first), though values don't need to be unique. This ordering establishes precedence rules between contexts should there be a conflict and multiple contexts define the same value. Defaults to 0.
	// Priority of the context attachment. All the contexts attached to a stack are sorted by priority (lowest first), though values don't need to be unique. This ordering establishes precedence rules between contexts should there be a conflict and multiple contexts define the same value. Defaults to `0`.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) ID of the stack to attach the context to
	// ID of the stack to attach the context to
	// +crossplane:generate:reference:type=github.com/aksel-allas-org/provider-spacelift/apis/stack/v1alpha1.Stack
	StackID *string `json:"stackId,omitempty" tf:"stack_id,omitempty"`

	// Reference to a Stack in stack to populate stackId.
	// +kubebuilder:validation:Optional
	StackIDRef *v1.Reference `json:"stackIdRef,omitempty" tf:"-"`

	// Selector for a Stack in stack to populate stackId.
	// +kubebuilder:validation:Optional
	StackIDSelector *v1.Selector `json:"stackIdSelector,omitempty" tf:"-"`
}

type AttachmentObservation struct {

	// (String) ID of the context to attach
	// ID of the context to attach
	ContextID *string `json:"contextId,omitempty" tf:"context_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the module to attach the context to
	// ID of the module to attach the context to
	ModuleID *string `json:"moduleId,omitempty" tf:"module_id,omitempty"`

	// (Number) Priority of the context attachment. All the contexts attached to a stack are sorted by priority (lowest first), though values don't need to be unique. This ordering establishes precedence rules between contexts should there be a conflict and multiple contexts define the same value. Defaults to 0.
	// Priority of the context attachment. All the contexts attached to a stack are sorted by priority (lowest first), though values don't need to be unique. This ordering establishes precedence rules between contexts should there be a conflict and multiple contexts define the same value. Defaults to `0`.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) ID of the stack to attach the context to
	// ID of the stack to attach the context to
	StackID *string `json:"stackId,omitempty" tf:"stack_id,omitempty"`
}

type AttachmentParameters struct {

	// (String) ID of the context to attach
	// ID of the context to attach
	// +crossplane:generate:reference:type=github.com/aksel-allas-org/provider-spacelift/apis/context/v1alpha1.Context
	// +kubebuilder:validation:Optional
	ContextID *string `json:"contextId,omitempty" tf:"context_id,omitempty"`

	// Reference to a Context in context to populate contextId.
	// +kubebuilder:validation:Optional
	ContextIDRef *v1.Reference `json:"contextIdRef,omitempty" tf:"-"`

	// Selector for a Context in context to populate contextId.
	// +kubebuilder:validation:Optional
	ContextIDSelector *v1.Selector `json:"contextIdSelector,omitempty" tf:"-"`

	// (String) ID of the module to attach the context to
	// ID of the module to attach the context to
	// +kubebuilder:validation:Optional
	ModuleID *string `json:"moduleId,omitempty" tf:"module_id,omitempty"`

	// (Number) Priority of the context attachment. All the contexts attached to a stack are sorted by priority (lowest first), though values don't need to be unique. This ordering establishes precedence rules between contexts should there be a conflict and multiple contexts define the same value. Defaults to 0.
	// Priority of the context attachment. All the contexts attached to a stack are sorted by priority (lowest first), though values don't need to be unique. This ordering establishes precedence rules between contexts should there be a conflict and multiple contexts define the same value. Defaults to `0`.
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// (String) ID of the stack to attach the context to
	// ID of the stack to attach the context to
	// +crossplane:generate:reference:type=github.com/aksel-allas-org/provider-spacelift/apis/stack/v1alpha1.Stack
	// +kubebuilder:validation:Optional
	StackID *string `json:"stackId,omitempty" tf:"stack_id,omitempty"`

	// Reference to a Stack in stack to populate stackId.
	// +kubebuilder:validation:Optional
	StackIDRef *v1.Reference `json:"stackIdRef,omitempty" tf:"-"`

	// Selector for a Stack in stack to populate stackId.
	// +kubebuilder:validation:Optional
	StackIDSelector *v1.Selector `json:"stackIdSelector,omitempty" tf:"-"`
}

// AttachmentSpec defines the desired state of Attachment
type AttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AttachmentInitParameters `json:"initProvider,omitempty"`
}

// AttachmentStatus defines the observed state of Attachment.
type AttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Attachment is the Schema for the Attachments API. spacelift_context_attachment represents a Spacelift attachment of a single context to a single stack or module, with a predefined priority.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,spacelift}
type Attachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AttachmentSpec   `json:"spec"`
	Status            AttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AttachmentList contains a list of Attachments
type AttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Attachment `json:"items"`
}

// Repository type metadata.
var (
	Attachment_Kind             = "Attachment"
	Attachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Attachment_Kind}.String()
	Attachment_KindAPIVersion   = Attachment_Kind + "." + CRDGroupVersion.String()
	Attachment_GroupVersionKind = CRDGroupVersion.WithKind(Attachment_Kind)
)

func init() {
	SchemeBuilder.Register(&Attachment{}, &AttachmentList{})
}
