// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha11 "github.com/coopnorge/provider-upjet-spacelift/apis/space/v1alpha1"
	v1alpha1 "github.com/coopnorge/provider-upjet-spacelift/apis/stack/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Attachment.
func (mg *Attachment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ContextID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ContextIDRef,
		Selector:     mg.Spec.ForProvider.ContextIDSelector,
		To: reference.To{
			List:    &ContextList{},
			Managed: &Context{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ContextID")
	}
	mg.Spec.ForProvider.ContextID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ContextIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.StackID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.StackIDRef,
		Selector:     mg.Spec.ForProvider.StackIDSelector,
		To: reference.To{
			List:    &v1alpha1.StackList{},
			Managed: &v1alpha1.Stack{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.StackID")
	}
	mg.Spec.ForProvider.StackID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.StackIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ContextID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ContextIDRef,
		Selector:     mg.Spec.InitProvider.ContextIDSelector,
		To: reference.To{
			List:    &ContextList{},
			Managed: &Context{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ContextID")
	}
	mg.Spec.InitProvider.ContextID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ContextIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.StackID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.StackIDRef,
		Selector:     mg.Spec.InitProvider.StackIDSelector,
		To: reference.To{
			List:    &v1alpha1.StackList{},
			Managed: &v1alpha1.Stack{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.StackID")
	}
	mg.Spec.InitProvider.StackID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.StackIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Context.
func (mg *Context) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SpaceID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SpaceIDRef,
		Selector:     mg.Spec.ForProvider.SpaceIDSelector,
		To: reference.To{
			List:    &v1alpha11.SpaceList{},
			Managed: &v1alpha11.Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SpaceID")
	}
	mg.Spec.ForProvider.SpaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SpaceID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.SpaceIDRef,
		Selector:     mg.Spec.InitProvider.SpaceIDSelector,
		To: reference.To{
			List:    &v1alpha11.SpaceList{},
			Managed: &v1alpha11.Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SpaceID")
	}
	mg.Spec.InitProvider.SpaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SpaceIDRef = rsp.ResolvedReference

	return nil
}
