// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/coopnorge/provider-upjet-spacelift/apis/namespaced/context/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this EnvironmentVariable.
func (mg *EnvironmentVariable) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ContextID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ContextIDRef,
		Selector:     mg.Spec.ForProvider.ContextIDSelector,
		To: reference.To{
			List:    &v1alpha1.ContextList{},
			Managed: &v1alpha1.Context{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ContextID")
	}
	mg.Spec.ForProvider.ContextID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ContextIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ContextID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ContextIDRef,
		Selector:     mg.Spec.InitProvider.ContextIDSelector,
		To: reference.To{
			List:    &v1alpha1.ContextList{},
			Managed: &v1alpha1.Context{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ContextID")
	}
	mg.Spec.InitProvider.ContextID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ContextIDRef = rsp.ResolvedReference

	return nil
}
