// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/coopnorge/provider-upjet-spacelift/apis/context/v1alpha1"
	v1alpha1environmentvariable "github.com/coopnorge/provider-upjet-spacelift/apis/environmentvariable/v1alpha1"
	v1alpha1gcpserviceaccount "github.com/coopnorge/provider-upjet-spacelift/apis/gcpserviceaccount/v1alpha1"
	v1alpha1module "github.com/coopnorge/provider-upjet-spacelift/apis/module/v1alpha1"
	v1alpha1space "github.com/coopnorge/provider-upjet-spacelift/apis/space/v1alpha1"
	v1alpha1stack "github.com/coopnorge/provider-upjet-spacelift/apis/stack/v1alpha1"
	v1alpha1apis "github.com/coopnorge/provider-upjet-spacelift/apis/v1alpha1"
	v1beta1 "github.com/coopnorge/provider-upjet-spacelift/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1environmentvariable.SchemeBuilder.AddToScheme,
		v1alpha1gcpserviceaccount.SchemeBuilder.AddToScheme,
		v1alpha1module.SchemeBuilder.AddToScheme,
		v1alpha1space.SchemeBuilder.AddToScheme,
		v1alpha1stack.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
